force-app/main/default/objects/Path_Activity__c/Path_Activity__c.object-meta.xml
<CustomObject>
    <label>Path Activity</label>
    <nameField>
        <label>Path Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Path Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Path_Activity__c/fields/Path_Sequence__c.field-meta.xml
<CustomField>
    <fullName>Path_Sequence__c</fullName>
    <label>Path Sequence</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trial_Activity__c/Trial_Activity__c.object-meta.xml
<CustomObject>
    <label>Trial Activity</label>
    <nameField>
        <label>Trial Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trial Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trial_Activity__c/fields/Current_Step__c.field-meta.xml
<CustomField>
    <fullName>Current_Step__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Step</label>
    <referenceTo>Path_Activity__c</referenceTo>
    <relationshipLabel>Trial Activities</relationshipLabel>
    <relationshipName>Trial_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Walkthrough__c/Walkthrough__c.object-meta.xml
<CustomObject>
    <label>Walkthrough</label>
    <nameField>
        <label>Walkthrough Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Walkthroughs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Walkthrough__c/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Activity</label>
    <referenceTo>Path_Activity__c</referenceTo>
    <relationshipLabel>Walkthroughs</relationshipLabel>
    <relationshipName>Walkthroughs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Walkthrough__c/fields/BodyText__c.field-meta.xml
<CustomField>
    <fullName>BodyText__c</fullName>
    <label>BodyText</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Walkthrough__c/fields/Close_Message__c.field-meta.xml
<CustomField>
    <fullName>Close_Message__c</fullName>
    <description>when the matching message is received, the walkthrough should close itself</description>
    <inlineHelpText>when the matching message is received, the walkthrough should close itself</inlineHelpText>
    <label>Close Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Walkthrough__c/fields/CSS__c.field-meta.xml
<CustomField>
    <fullName>CSS__c</fullName>
    <defaultValue>"slds-popover,slds-popover_walkthrough,slds-nubbin_left,no-pointer"</defaultValue>
    <description>css that should be applied to the popover.</description>
    <inlineHelpText>css that should be applied to the popover.</inlineHelpText>
    <label>CSS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Walkthrough__c/fields/Manual_Grouping__c.field-meta.xml
<CustomField>
    <fullName>Manual_Grouping__c</fullName>
    <inlineHelpText>use this field to group popovers that don't have a lookup to a path activity</inlineHelpText>
    <label>Manual Grouping</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Walkthrough__c/fields/Next_Button_Action_Override__c.field-meta.xml
<CustomField>
    <fullName>Next_Button_Action_Override__c</fullName>
    <description>will be c.nextCalled if no override is provided</description>
    <label>Next Button Action Override</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Walkthrough__c/fields/Next_Button_Label__c.field-meta.xml
<CustomField>
    <fullName>Next_Button_Label__c</fullName>
    <defaultValue>"Next"</defaultValue>
    <label>Next Button Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Walkthrough__c/fields/Open_on_RecordId__c.field-meta.xml
<CustomField>
    <fullName>Open_on_RecordId__c</fullName>
    <label>Open on RecordId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Walkthrough__c/fields/Open_on_URL__c.field-meta.xml
<CustomField>
    <fullName>Open_on_URL__c</fullName>
    <inlineHelpText>open the popover if the current url contains this text</inlineHelpText>
    <label>Open on URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Walkthrough__c/fields/Selector__c.field-meta.xml
<CustomField>
    <fullName>Selector__c</fullName>
    <description>css selector for the element that the popover should be next to</description>
    <inlineHelpText>css selector for the element that the popover should be next to</inlineHelpText>
    <label>Selector</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Walkthrough__c/fields/Show_Close_Button__c.field-meta.xml
<CustomField>
    <fullName>Show_Close_Button__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show Close Button</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Walkthrough__c/fields/Show_Next_Button__c.field-meta.xml
<CustomField>
    <fullName>Show_Next_Button__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Show Next Button</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TrialUtilities.cls
public with sharing class TrialUtilities {

	@AuraEnabled
	public static string getUserId() {
		return UserInfo.getUserId();
	}

	@AuraEnabled
	public static string getTrialActivityId(){
		Trial_Activity__c TA = [select id, Current_Step__c from Trial_Activity__c][0];
		//if there isn't a current step, we'll set it to the default one
		if (TA.Current_Step__c == null){
			Path_Activity__c PA = [select Id from Path_Activity__c where Path_Sequence__c = 1];
			TA.Current_Step__c = PA.Id;
			update TA;
		}
		return TA.Id;
	}

	@AuraEnabled
	public static list<Walkthrough__c> getWalkthroughsByActivity(id activityId){
		return [select Id, Name, BodyText__c, CSS__c, Header__c, Open_on_RecordId__c, Open_on_URL__c,
			Next_Button_Action_Override__c, Next_Button_Label__c, Selector__c, Sequence__c, Show_Close_Button__c, Show_Next_Button__c, Close_Message__c
			from Walkthrough__c
			where Activity__c =: activityId and Completed__c = false
			order by Sequence__c ASC];
	}

	@AuraEnabled
	public static list<Walkthrough__c> getWalkthroughsByGrouping(string manualGrouping){
		return [select Id, Name, BodyText__c, CSS__c, Header__c, Open_on_RecordId__c, Open_on_URL__c,
			Next_Button_Action_Override__c, Next_Button_Label__c, Selector__c, Sequence__c, Show_Close_Button__c, Show_Next_Button__c, Close_Message__c
			from Walkthrough__c
			where Manual_Grouping__c =: manualGrouping and Completed__c = false
			order by Sequence__c ASC];
	}

}